config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :end_users, :controllers => { :registrations => 'end_users/registrations' }
  root "homes#top"
  get	'/end_users/finished' => 'end_users#finished'
  patch '/end_users/withdraw' =>	'end_users#withdraw'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy ] do
      resources:item_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  resources :end_users,only: [:show, :edit, :update, :index ] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get 'search'
    end
  end
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  resources :notifications, only: [:index, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  # 新着順
  #optional: true =item_id にnilを許容するもの(フォロー通知が有効にするため)
  belongs_to :item, optional: true
  belongs_to :item_comment, optional: true
  belongs_to :visitor, class_name: 'EndUser', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'EndUser', foreign_key: 'visited_id', optional: true
  belongs_to :room, optional: true
  belongs_to :message, optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    #current_end_userの投稿に紐づいた通知一覧
    @notifications = current_end_user.passive_notifications
    #@notificationの中でまだ確認していない(indexに一度も遷移してない)通知のみ
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    redirect_to request.referer
  end

  def destroy_all
    # 通知を全削除
    @notifications = current_end_user.passive_notifications.destroy_all
    redirect_to request.referer
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper



  def notification_form(notification)
     @visitor = notification.visitor
     @comment = nil
     your_item = link_to 'あなたの投稿', item_path(notification), style: "font-weight: bold;"
     @visitor_comment = notification.item_comment_id
     # notification.actionがfollowかlikeかcommentか
     case notification.action
       when "follow" then
        tag.a(notification.visitor.name, href:end_user_path(@visitor), style: "font-weight: bold;")+"さんがあなたをフォローしました!"
       when "favorite" then
        tag.a(notification.visitor.name, href:end_user_path(@visitor), style: "font-weight: bold;")+"さんが"+tag.a('あなたの投稿', href:item_path(notification.item_id), style:"font-weight: bold;")+"にいいねしました!"
       when "item_comment" then
        @comment = ItemComment.find_by(id: @visitor_comment)&.comment
        tag.a(@visitor.name, href: end_user_path(@visitor), style: "font-weight: bold;")+"さんが"+tag.a('あなたの投稿', href:item_path(notification.item_id), style:"font-weight: bold;")+"にコメントしました!"
     end
  end

  def unchecked_notifications
    @notifications = current_end_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<% item = notification.item %>

<div>
 <% if notification.action=='dm' %>
   <%= link_to end_user_path(visitor) do %>
     <%= visitor.name %>
   <% end %>
    さんがあなたにChatを送りました！
    <span><%= time_ago_in_words(notification.created_at).upcase %>
          <%= link_to notification_path(notification.id), method: :delete do %>
           <i class="fas fa-trash-alt" style="color: #e6c5cf"></i><% end %>
    </span>
 <% else %>
   <%= notification_form(notification) %>
   <span><%= time_ago_in_words(notification.created_at).upcase %>
         <%= link_to notification_path(notification.id), method: :delete do %>
          <i class="fas fa-trash-alt" style="color: #e6c5cf"></i><% end %>
   </span>
         <% if !@comment.nil? %>
          <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @comment %></p>
         <% end %>
 <% end %>
</div>
<br>

app/views/notifications/_sign.html.erb
 <h6><%= link_to notifications_path, class: "fas_button2" do %>
  通知を見る
  <% if unchecked_notifications.any? %>
    <span class="fa-stack">
      <i class= "far fa-bell fa-stack-2x" style="font-size: 1.5em; color: #af9dc0;"></i>
      <i class= "fas fa-circle n-circle fa-2x"></i>
    </span>
  <% else %>
    <i class="far fa-bell fa-lg" style="font-size: 1.5em;"></i>
  <% end %>
<% end %>
</h6>

app/views/notifications/index.html.erb
<% notifications = @notifications.where.not(visitor_id: current_end_user.id) %>
    <br>
   
    <div class="container">
    <div class ="col-md-12">
      <div class="col-md-7">
    <%= link_to destroy_all_notifications_path, method: :delete do %>
        <i class="fas fa-trash-alt" style="color: #af9dc0"></i>
        <h7 style="color: #af9dc0;">全削除</h7>
    <% end %>
     </div>
    <hr>
      <div class="row align-items-center">
        <div class="col-auto mx-auto">
            <% if notifications.exists? %>
                <%= render notifications %>
            <% else %>
                <p>通知はありません</p>
            <% end %>
        </div>
      </div>
    </div>
</div>