config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :end_users, :controllers => { :registrations => 'end_users/registrations' }
  root "homes#top"
  get	'/end_users/finished' => 'end_users#finished'
  patch '/end_users/withdraw' =>	'end_users#withdraw'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy ] do
      resources:item_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  resources :end_users,only: [:show, :edit, :update, :index ] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get 'search'
    end
  end
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  resources :notifications, only: [:index, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :notifications, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_end_user!

  def create
    @room = Room.create
    # 現在ログインしてるユーザー：@roomにひもづくidと、現在ログインしているユーザーのidを保存させる
    @entry1 = Entry.create(room_id: @room.id, end_user_id: current_end_user.id)
    # フォローされている側の情報をEntriesテーブルに保存
    @entry2 = Entry.create(params.require(:entry).permit(:end_user_id, :room_id).merge(room_id: @room.id))
    #createと同時に、チャットルームが開くように
      redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    #Entriesテーブルに、現在ログインしているユーザーのidとそれにひもづいたチャットルームのidがあるか検索
    if Entry.where(end_user_id: current_end_user.id, room_id: @room.id).present?
      @messages = @room.messages.all
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def room_params
      params.require(:room).permit(:end_user_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<br>
<div class="left-button">
  <%= link_to "Member一覧", end_users_path, class: "fas_button_border" %>
</div>
<div class="container">
  <div class="row align-items-center">
    <div class="col-auto mx-auto">
      <br>
      <h4 class ="rooms-title"><i class="far fa-comments"></i> Chat Room</h4>
      </div>
    </div>
  <div class="container">
    <div class="row align-items-center">
      <% @entries.each do |e| %>
        <div class="end_user">
            <strong><a href="/end_users/<%= e.end_user.id %>">
            <%= image_tag e.end_user.get_profile_image(30,30), class:"mt-3 rounded-circle"; %>
            <%= e.end_user.name %></a>
          </strong>
        </div>
      <% end %>
     </div>
    </div>
<hr>
<div class="row align-items-center">
  <div class="col-auto mx-auto">
    <div class="chats">
      <div class="chat">
        <% if @messages.present? %>
          <% @messages.each do |m| %>
          <div class="chat-box">
            <div class="chat-face">
              <%= image_tag m.end_user.get_profile_image(30,30), class:"mt-3 rounded-circle" %>
              <%= m.end_user.name %>: <span class="word" style="width: 400px;"><%=safe_join(m.message.split("\n"),tag(:br))%></span>
            </div>
            <div class="chat-room">
              <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
              <% if m.end_user == current_end_user %>
                <%= link_to message_path(m.id), method: :delete, class: "fas_button_border" do %>
                 <i class="fas fa-trash-alt"></i>
                <% end %>
              <% end %>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
      <br>
        <div class="posts">
          <%= form_with model: @message do |f| %>
            <%= f.text_field :message, placeholder: "メッセージを入力", size: 30, class:"form-text-field" %>
              <%= f.hidden_field :room_id, value: @room.id %>
              <%= f.hidden_field :end_user_id, value: current_end_user.id %>
                <%= f.submit "Send", class: 'form-submit'%>
          <% end %>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>