config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :end_users, :controllers => { :registrations => 'end_users/registrations' }
  root "homes#top"
  get	'/end_users/finished' => 'end_users#finished'
  patch '/end_users/withdraw' =>	'end_users#withdraw'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy ] do
      resources:item_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  resources :end_users,only: [:show, :edit, :update, :index ] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get 'search'
    end
  end
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  resources :notifications, only: [:index, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_one_attached :profile_image
  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # @end_user.itemsのように、@end_user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  #自分が作った通知(active_notifications)自分宛の通知(passive_notifications)
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :view_counts, dependent: :destroy



  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォローしたときの処理
  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end
  #フォロー外す時
  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end
  #フォローしてるか判定
  def following?(end_user)
    followings.include?(end_user)
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def create_notification_follow!(current_end_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_end_user.id, id, 'follow' ])
    if temp.blank?
      notification = current_end_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
        )
    notification.save if notification.valid?
    end
  end

  def self.guest
      find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.name ="guestuser"
    end
  end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :reject_inactive_end_user, only: [:create]
  before_action :end_user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  def guest_sign_in
    end_user = EndUser.guest
    sign_in end_user
    redirect_to end_user_path(end_user), notice: 'guestとしてログインしました!'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  def end_user_state
      @end_user = EndUser.find_by(name: params[:end_user][:name].downcase)
      return if !@end_user
      if (@end_user.valid_password?(params[:end_user][:password]) && (@end_user.active_for_authentication? == false))
        redirect_to new_end_user_registration_path
      end
  end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :authenticate_end_user!, except: [:top, :index]
  before_action :ensure_guest_end_user, only: [:edit]
  before_action :set_q, only: [:index, :search]

    def index
      @end_users = EndUser.page(params[:page])
    end

    def show
      @end_user = EndUser.find(params[:id])
      # roomがcreateされた時に、ログインしているユーザーと、「チャットへ」を押されたユーザーの両方をEntriesテーブルに記録
      @currentEndUserEntry = Entry.where(end_user_id: current_end_user.id)
      @EndUserEntry = Entry.where(end_user_id: @end_user.id)
      # 現在ログインしているユーザーではない時
      unless @end_user.id == current_end_user.id
        # roomsが作成されている場合と作成されていない場合に条件分岐
        # 作成されている時、eachで一人づつ取り出し、Entriesテーブル内のroom_idが共通しているのユーザー同士に変数を指定
        @currentEndUserEntry.each do |cu|
          @EndUserEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        if @isRoom
        else
          @room = Room.new
          @entry = Entry.new
        end
      end
      # タグ検索 タグがあれば、end_userのitemタグからitemを絞り込み
      items = params[:tag_id].present? ? Tag.find(params[:tag_id]).items : @end_user.items.all
      @tag_id = params[:tag_id].present? ? params[:tag_id] : nil
        if params[:sort] == "star"
          items = items.where(end_user_id: params[:id]).order("star DESC")
        elsif params[:sort] == "create"
          items = items.where(end_user_id: params[:id]).order(created_at: :desc)
        else
          items = items.where(end_user_id: params[:id])
            to = Time.current.at_end_of_day
            from = (to - 6.day).at_beginning_of_day
            items = items.all.sort { | a, b |
              b.favorites.where(created_at: from...to).size <=>
              a.favorites.where(created_at: from...to).size
            }
        end
        @items = Kaminari.paginate_array(items).page(params[:page])
        @notifications = current_end_user.passive_notifications
    end

    def edit
      @end_user = EndUser.find(params[:id])
       if @end_user == current_end_user
          render "edit"
       else
          redirect_to edit_end_user_path(current_end_user)
       end
    end

    def update
      @end_user = EndUser.find(params[:id])
      if @end_user.update(end_user_params)
        redirect_to end_user_path(@end_user.id)
        flash[:notice] ="Updated profile successfully!"
      else
        render :edit
      end
    end

    def search
      @results = @q.result
    end

    def finished
      @end_user = current_end_user
    end

    def withdraw
      @end_user = current_end_user
      @end_user.update(is_deleted: true)
      reset_session
      redirect_to root_path
    end

    private

    def set_q
      @q = EndUser.ransack(params[:q])
    end

    def end_user_params
      params.require(:end_user).permit(:name, :introduction, :profile_image, :is_deleted, tag_ids: [])
    end

    def correct_end_user
      @end_user = EndUser.find(params[:id])
       redirect_to(end_user_session_path(end_user_id)) unless @end_user == current_end_user
    end

    def ensure_guest_end_user
      @end_user = EndUser.find(params[:id])
      if @end_user.name == "guestuser"
        redirect_to end_user_path(current_end_user), notice: 'ゲストはプロフィール編集できません。'
      end
    end
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/_box.html.erb
<div class="col-lg-10 col-md-auto text-center text-md-left" >
   <h4><i class="far fa-gem"></i> <%= @end_user.name %> 's Items</h4>
    <div class="row justify-content-end text-md-center">
      <%= link_to new_item_path do %>
      <button class="fas_button_round"><i class="fas fa-plus-circle" style="color: #af9dc0;"></i> Post</button>
      <% end %>
    </div>
      <div class= "text-center">
      <%= render 'items/tagshow' %>
      <%= render 'end_users/sort', {end_user: end_user, tag_id: tag_id} %>
      </div>
    <% items.each do |item| %>
      <div class="d-inline-flex p-2 bd-highlight">
        <div class="p-2 flex-fill bd-highlight" >
          <div class="inline-block ">
            <%= link_to item_path(item.id) do %>
            <%= image_tag item.get_image, size:'110x110', class: "thumb-110 shadow p-3 mb-4 bg-body round" %>
            <% end %>
            <div class="favorite_buttons_<%= item.id %>"><%= render 'favorites/favorite', item: item %>
            </div>
            <h5><% item.tags.each do |tag| %>
                <span class= 'badge badge1'><a style="color:#af9dc0"><%= tag.name %></a></span>
                <% end %></h5>
            <h5><i class="far fa-gem"></i> Item</h5>
            <p class="word" style="width: 140px;"><%= link_to item.name,item, class: "item_#{item.id}" %></p>
            <h5><i class="fas fa-pen"></i> Point</h5>
            <p class="word" style="width: 140px;"><%=safe_join(item.body.split("\n"),tag(:br))%></p>
          </div>
        </div>
      </div>
    <% end %>
     <div class="row justify-content-center">
      <%= paginate items %>
     </div>
</div>

app/views/end_users/_entry.html.erb
<% unless end_user.id == current_end_user.id %>
  <!--相互フォロー状態の時-->
  <% if (current_end_user.following? end_user) && (end_user.following? current_end_user) %>
  <!--すでにルームが作成している時と作成されていない時の条件分岐-->
    <% if isRoom == true %>
      <p class="end-user-show-room"><a href="/rooms/<%= roomId %>" class="fas_button2">Chat Room <i class="fas fa-comment-dots"></i></a></p>
    <% else %>
      <!--レコードは、親Roomテーブルと子Entriesテーブル両方に保存する-->
      <%= form_with model: room, url: rooms_path do |f| %>
       <%= fields_for entry do |e| %>
       <!--Entriesテーブルのレコードにはend_user_idを送る-->
         <%= e.hidden_field :end_user_id, value: end_user.id %>
      <% end %>
       <%= f.submit "Start Chat", class:"fas_button2"%>
       <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/end_users/_search.html.erb
<div class="row justify-content-center">
  <%= search_form_for q, url: search_end_users_path do |f| %>
    <%= f.label :name_cont, 'Member検索' %>
    <%= f.text_field :name_cont %>
    <%= f.submit '検索' %>
  <% end %>
</div>
<br>

app/views/end_users/_sort.html.erb
<div class= "container">
  <div class="row justify-content-center">
    <% if tag_id.nil? %>
    <%= link_to end_user_path(end_user, {sort: "create"}) do %>新着順<% end %>
    |
    <%= link_to end_user_path(end_user, {sort: "star"}) do %>星評価順<% end %>
    <% else %>
    <%= link_to end_user_path(end_user, {sort: "create", tag_id: tag_id}) do %>新着順<% end %>
    |
    <%= link_to end_user_path(end_user, {sort: "star", tag_id: tag_id}) do %>星評価順<% end %>
    <% end %>
  </div>
</div>

app/views/end_users/edit.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="col-auto mx-auto">
      <br>
      <h3><i class="far fa-user"></i> Edit User</h3>
        <%= form_with model: @end_user, url: end_user_path(@end_user.id), method: :patch do |f| %>
        <div class="field">
          <%= f.label :Profile写真 %><br />
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :introduction %><br />
          <%= f.text_area :introduction %>
        </div>
        <br />
        <div class="field">
          <%= f.submit "Update", class: 'fas_button_round' %>
        </div>
        <% end %>
        <br>
        <div class="field">
          <%= link_to end_users_finished_path, class: "fas_button2" do %>
           退会する<% end %>
        </div>
    </div>
  </div>
</div>
<br>

app/views/end_users/finished.html.erb
<div class='container'>
    <div class="col-sm-12 col-md-8 col-lg-8 px-5 px-sm-0 mx-auto">
      <br><div class= "text-center">
        <h2>本当に退会しますか？</h2>
        <p>退会すると、会員情報や</p>
        <p>これまでの購入履歴が閲覧できなくなります。</p>
        <p>退会する場合は、「退会する」をクリックしてください。</p>
      </div>
      <div class= "text-center">
        <%= link_to '退会しない', end_user_path(current_end_user.id), class: 'fas_button_round' %><br />
        <br>
        <%= link_to "退会する", end_users_withdraw_path, method: :patch, class: "fas_button2" %>
      </div>
    </div>
</div>

app/views/end_users/index.html.erb
  <br>
  <h2 class= "text-center"><i class="fas fa-users"></i> Members</h2>
  <br>
  <%= render 'end_users/search', q: @q %>
  <div class="col-md-12">
    <div class="row justify-content-center">
      <% @end_users.each do |end_user| %>
        <div class="pl-4">
          <%= link_to end_user_path(end_user) do %>
          <%= image_tag end_user.get_profile_image(100,100) ,class: "shadow p-3 mb-3 bg-body round" %>
          <% end %>
          <p class="color: #af9dc0;"><i class="fas fa-user"></i>:
            <%= link_to end_user_path(end_user) do %>
            <%= end_user.name %><% end %>
          </p>
          <% if end_user.introduction.nil? %>
            <p><i class="fas fa-pen-square"></i><% end_user.introduction %></p>
          <% else %>
            <p class="word" style="width: 140px;"><i class="fas fa-pen-square"></i>: <%=safe_join(end_user.introduction.split("\n"),tag(:br))%></p>
           <!--#紹介文が「空」じゃない時は正常に反映する-->
          <% end %>
          <div class="card-body text-center">
              <% unless current_end_user == end_user %>
                <% if current_end_user.following?(end_user) %>
                 <%= link_to "フォローを外す", end_user_relationships_path(end_user.id), method: :delete, class: "fas_button2" %>
                <% else %>
                 <%= link_to "フォローする", end_user_relationships_path(end_user.id), method: :post, class: "fas_button2" %>
                <% end %>
              <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <div class="row justify-content-center">
    <%= paginate @end_users %>
  </div>

app/views/end_users/search.html.erb
<br>
<h2 class= "text-center"><i class="fas fa-users"></i> Members</h2>
  <br>
    <div class="col-md-12">
      <div class="row justify-content-center">
      <% if @results.exists? %>
        <% @results.each do |end_user| %>
          <div class="pl-4">
            <%= link_to end_user_path(end_user) do %>
              <%= image_tag end_user.get_profile_image(100,100) ,class: "shadow p-3 mb-3 bg-body round" %>
            <% end %>
            <p><i class="fas fa-user"></i>:<%= end_user.name %></p>

              <% if end_user.introduction.nil? %>
                <i class="fas fa-pen-square"></i>:<% end_user.introduction %>
              <% else %>
               <p class="word" style="width: 140px;"><i class="fas fa-pen-square"></i> <%=safe_join(end_user.introduction.split("\n"),tag(:br))%></p>
               <!--#紹介文が「空」じゃない時は正常に反映-->
              <% end %>

            <div class="card-body text-center">
                <% unless current_end_user == end_user %>
                  <% if current_end_user.following?(end_user) %>
                   <%= link_to "フォローを外す", end_user_relationships_path(end_user.id), method: :delete, class: "fas_button2" %>
                  <% else %>
                   <%= link_to "フォローする", end_user_relationships_path(end_user.id), method: :post, class: "fas_button2" %>
                  <% end %>
                <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>Memberはいません</p>
      <% end %>
      </div>
    </div>
<br>
<div class="row justify-content-center">
  <%= link_to end_users_path, class: 'fas_button_round' do %>
  Back<% end %>
</div>
<br>

app/views/end_users/show.html.erb
<br>
<div class="container">
  <div class="row align-items-center">
    <div class="col-auto mx-auto">
      <h2><%= @end_user.name %> 's <i class="fas fa-box-open"></i> BOX</h2>
    </div>
  </div>
</div>
<h5 class="text-center" style="color: #76a1b8"><%= flash[:notice] %></h5>
<div class="container">
  <div class="row">
    <div class="col-lg-2 col-md-auto text-center text-md-left">
      <h4><i class="far fa-user"></i> Profile</h4>
       <br>
       <div class="row justify-content-center">
          <div class="pl">
            <%= image_tag @end_user.get_profile_image(100,100) ,class: "shadow p-3 mb-2 bg-body rounded-circle" %>
            <h5 style="color:#e6c5cf">Name</h5><p><%= @end_user.name %></p>
            <% if @end_user.introduction.nil? %>
              <h5 style="color:#e6c5cf">Introduction</h5><p><% @end_user.introduction %></p>
            <% else %>
              <h5 style="color:#e6c5cf">Introduction</h5><p class="word" style="width: 140px;"><%=safe_join(@end_user.introduction.split("\n"),tag(:br))%></p>
             <!--# 紹介文が「空」じゃない時は正常に反映-->
            <% end %>
            <p><% if current_end_user == @end_user %>
                 <%= link_to edit_end_user_path(@end_user) do %>
                 <button class="fas_button_borderradius"><i class="far fa-edit"></i> Edit</button>
                 <% end %>
               <% end %>
            </p>
            <p style="color:#e6c5cf">
              follows<%= link_to end_user_followings_path(@end_user.id) do %>
                <%= @end_user.followings.count %>
              <% end %> </p>
            <p style="color:#e6c5cf">followers<%= link_to end_user_followers_path(@end_user.id) do %>
                <%= @end_user.followers.count %>
              <% end %></p>

            <p><% unless current_end_user == @end_user %>
                <% if current_end_user.following?(@end_user) %>
                 <%= link_to "フォローを外す", end_user_relationships_path(@end_user.id), method: :delete, class: "fas_button2" %>
                <% else %>
                 <%= link_to "フォローする", end_user_relationships_path(@end_user.id), method: :post, class: "fas_button2" %>
                <% end %>
               <% end %>
            </p>
            <p><%= render 'end_users/entry', end_user: @end_user, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry %></p>
            <p><% if @end_user == current_end_user %>
               <%= render 'notifications/sign' %>
               <% end %>
            </p>
            <br>
          </div>
       </div>
    </div>
    <%= render 'end_users/box', end_user: @end_user, tag_id: @tag_id, items: @items %>
  </div>
</div>