config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :end_users, :controllers => { :registrations => 'end_users/registrations' }
  root "homes#top"
  get	'/end_users/finished' => 'end_users#finished'
  patch '/end_users/withdraw' =>	'end_users#withdraw'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy ] do
      resources:item_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  resources :end_users,only: [:show, :edit, :update, :index ] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    collection do
      get 'search'
    end
  end
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  resources :notifications, only: [:index, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_one_attached :profile_image
  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # @end_user.itemsのように、@end_user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  #自分が作った通知(active_notifications)自分宛の通知(passive_notifications)
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :view_counts, dependent: :destroy



  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォローしたときの処理
  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end
  #フォロー外す時
  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end
  #フォローしてるか判定
  def following?(end_user)
    followings.include?(end_user)
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def create_notification_follow!(current_end_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_end_user.id, id, 'follow' ])
    if temp.blank?
      notification = current_end_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
        )
    notification.save if notification.valid?
    end
  end

  def self.guest
      find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.name ="guestuser"
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :room, optional: true
  belongs_to :end_user, optional: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :end_user, optional: true
  belongs_to :item, optional: true
  validates_uniqueness_of :item_id, scope: :end_user_id
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :end_user
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  has_many :favorites, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  has_many :item_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  validates :name, presence: true, length: { in: 1..30 }
  validates :body, presence: true, length: { maximum: 100 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo2.png')
      image.attach(io: File.open(file_path), filename: 'default-image.png', content_type: 'image/png')
    end
    image
  end

  def favorited_by?(end_user)
    favorites.where(end_user_id: end_user.id).exists?
  end

  def create_notification_by(current_end_user)
    notification = current_end_user.active_notifications.new(
      item_id: id,
      visited_id: end_user_id,
      action: "favorite"
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_end_user, item_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = ItemComment.select(:end_user_id).where(item_id: id).where.not(end_user_id: current_end_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_end_user, item_comment_id, temp_id['end_user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_end_user, item_comment_id, end_user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_end_user, item_comment_id, visited_id)
    # コメントは複数回するため、１つの投稿に複数回通知する
    notification = current_end_user.active_notifications.new(
      item_id: id,
      item_comment_id: item_comment_id,
      visited_id: visited_id,
      action: 'item_comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
        notification.save if notification.valid?
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :end_user
  belongs_to :item
  has_many :notifications, dependent: :destroy
  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord
  belongs_to :item
  belongs_to :tag
end

app/models/message.rb
class Message < ApplicationRecord
  # 空で送信しない
  validates :message, presence: true, length: { maximum: 200 }
  belongs_to :end_user, optional: true
  belongs_to :room, optional: true
  has_many :notifications, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  # 新着順
  #optional: true =item_id にnilを許容するもの(フォロー通知が有効にするため)
  belongs_to :item, optional: true
  belongs_to :item_comment, optional: true
  belongs_to :visitor, class_name: 'EndUser', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'EndUser', foreign_key: 'visited_id', optional: true
  belongs_to :room, optional: true
  belongs_to :message, optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "EndUser"
  belongs_to :followed, class_name: "EndUser"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :notifications, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :item_tags, dependent: :destroy
  has_many :items, through: :item_tags
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :end_user
  belongs_to :item
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class='container-fluid position: fixed;' style= "background-color: #bdd8dd">
  	<div class="row">
      <div class="col-auto mx-auto ">
  	  <br>
    	  <p class="text-white text-center">Copyright © Favorites Box, Inc.</p>
      </div>
    </div>
    <div class="row">
    <div class="col-auto mx-auto n-icon width: 40%; height: 40%;"  >
    <a class="" href="#"><i class="fab fa-twitter fa-2x " style="color:#af9dc0"></i></a>
    <a class="" href="#"><i class="fab fa-instagram fa-2x " style="color:#af9dc0"></i></a>
    <a class="" href="#"><i class="fab fa-facebook fa-2x " style="color:#af9dc0"></i></a>
    </div>
  </div>
    <br>

  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-expand-md navbar-expand-sm navbar-light" style="background-color: #bdd8dd">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><%= image_tag 'Fave', size: '100x100' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if end_user_signed_in? %>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to end_user_path(current_end_user.id), class: 'nav-link text-light' do %>
          <i class="far fa-user"></i> My Page
          <% end %></button>
        </li>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to items_path, class: 'nav-link text-light' do %>
          <i class="far fa-gem"></i> Items Box
          <% end %></button>
        </li>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to end_users_path, class: 'nav-link text-light' do %>
          <i class="fas fa-users"></i> Members
          <% end %></button>
        </li>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to destroy_end_user_session_path, method: :delete, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-out-alt"></i> Log Out
          <% end %></button>
        </li>
        <% else %>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to end_users_guest_sign_in_path, class: 'nav-link text-light', method: :post do %>
          <i class="fas fa-sign-in-alt"></i> Guest
          <% end %></button>
        </li>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to items_path, class: 'nav-link text-light' do %>
          <i class="far fa-gem"></i> Items Box
          <% end %></button>
        </li>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to new_end_user_registration_path, class: 'nav-link text-light' do %>
          <i class="fas fa-users"></i> Join Us
          <% end %></button>
        </li>
        <li class="nav-item">
          <button class="fas_button_borderbackround"><%= link_to new_end_user_session_path, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-in-alt"></i> Log In
          <% end %></button>
        </li>
        <% end %>
        </ul>
      </div>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favorites Box</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style= "background-color: #fff">
    <%= render 'layouts/header' %>
     <main class="mb-auto">
      <%= yield %>
     </main>
    <%= render 'layouts/footer' %>
  </body>
</html>